[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = [
    "pip install --no-cache-dir --timeout=300 -r requirements.txt"
]

[start]
cmd = "python frontend/app.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9"