[deploy]
startCommand = "python start.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
ENVIRONMENT = "production"
RAILWAY_ENVIRONMENT_NAME = "production"