[deploy]
startCommand = "python frontend/app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
ENVIRONMENT = "production"
RAILWAY_ENVIRONMENT_NAME = "production"