[build]
builder = "nixpacks"
buildTimeout = 1800  # 30 minutes instead of default 10

[deploy]
startCommand = "python frontend/app.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
ENVIRONMENT = "production"
RAILWAY_ENVIRONMENT_NAME = "production"